AWSTemplateFormatVersion: '2010-09-09'
Description: 'Auto Scaling Group and Load Balancer for WordPress HA'

Parameters:
  NetworkStackName:
    Type: String
    Description: Name of the network stack
  
  DatabaseStackName:
    Type: String
    Description: Name of the database stack
  
  KeyName:
    Type: String
    Description: EC2 Key Pair name
  
  DBPassword:
    Type: String
    NoEcho: true
    Description: Database password
  
  InstanceType:
    Type: String
    Default: t3.micro

Resources:
  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Application Load Balancer
      VpcId: 
        Fn::ImportValue: !Sub ${NetworkStackName}-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Type: application
      Subnets:
        - Fn::ImportValue: !Sub ${NetworkStackName}-PublicSubnet1Id
        - Fn::ImportValue: !Sub ${NetworkStackName}-PublicSubnet2Id
      SecurityGroups:
        - !Ref ALBSecurityGroup

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: HTTP
      VpcId: 
        Fn::ImportValue: !Sub ${NetworkStackName}-VpcId
      HealthCheckPath: /
      HealthCheckProtocol: HTTP

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref ALBTargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        ImageId: ami-0c02fb55956c7d316
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - Fn::ImportValue: !Sub ${DatabaseStackName}-WebServerSecurityGroupId
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd php php-mysql
            
            cd /var/www/html
            wget https://wordpress.org/latest.tar.gz
            tar -xzf latest.tar.gz --strip-components=1
            
            cp wp-config-sample.php wp-config.php
            sed -i "s/database_name_here/wordpress/" wp-config.php
            sed -i "s/username_here/admin/" wp-config.php
            sed -i "s/password_here/${DBPassword}/" wp-config.php
            sed -i "s/localhost/${DatabaseStackName}-DBEndpoint/" wp-config.php
            
            chown -R apache:apache /var/www/html
            chmod -R 755 /var/www/html
            
            systemctl enable httpd
            systemctl start httpd

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: 1
      MaxSize: 3
      DesiredCapacity: 2
      VPCZoneIdentifier:
        - Fn::ImportValue: !Sub ${NetworkStackName}-PublicSubnet1Id
        - Fn::ImportValue: !Sub ${NetworkStackName}-PublicSubnet2Id
      TargetGroupARNs:
        - !Ref ALBTargetGroup
      HealthCheckType: ELB

Outputs:
  LoadBalancerDNS:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
    Export:
      Name: !Sub ${AWS::StackName}-LoadBalancerDNS